name: "Code Quality using codeQL"

permissions:
  contents: read
  security-events: write

on:
  workflow_call:
    inputs:
      languages:
        type: string
        required: true
        description: JSON array of CodeQL supported languages, e.g. '["go","javascript"]'

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJSON(inputs.languages) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v4

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        upload: never
